#!/usr/bin/env python3

# ============================================================================
# DEBUG VERSION - Auto-generated by make-awesome.py
# ============================================================================

import os
import sys
from pathlib import Path
from datetime import datetime
import os as _os_timing, time as _time_module

# Debug configuration (default 0, triggered by tw --debug=2)
DEBUG_MODE = 0

tw_debug_level = os.environ.get('TW_DEBUG', '0')
try:
    tw_debug_level = int(tw_debug_level)
except ValueError:
    tw_debug_level = 0

debug_active = DEBUG_MODE == 1 or tw_debug_level >= 2

def get_log_dir():
    """Log dir respects TW_TASK_DIR for dev/test isolation."""
    import os as _os
    task_dir = Path(_os.environ.get('TW_TASK_DIR', str(Path.home() / '.task')))
    log_dir = task_dir / 'logs' / 'debug'
    log_dir.mkdir(parents=True, exist_ok=True)
    return log_dir

if debug_active:
    DEBUG_LOG_DIR = get_log_dir()
    DEBUG_SESSION_ID = datetime.now().strftime("%Y%m%d_%H%M%S")
    try:
        script_name = Path(__file__).stem
    except:
        script_name = Path(sys.argv[0]).stem if sys.argv else "script"
    DEBUG_LOG_FILE = DEBUG_LOG_DIR / f"{script_name}_debug_{DEBUG_SESSION_ID}.log"
    
    def debug_log(message, level=1):
        if debug_active and tw_debug_level >= level:
            timestamp = datetime.now().strftime("%H:%M:%S.%f")[:-3]
            log_line = f"{timestamp} [DEBUG-{level}] {message}\n"
            with open(DEBUG_LOG_FILE, "a") as f:
                f.write(log_line)
            print(f"\033[34m[DEBUG-{level}]\033[0m {message}", file=sys.stderr)
    
    with open(DEBUG_LOG_FILE, "w") as f:
        f.write("=" * 70 + "\n")
        f.write(f"Debug Session - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"Script: {script_name}\n")
        f.write(f"TW_DEBUG Level: {tw_debug_level}\n")
        f.write("=" * 70 + "\n\n")
    debug_log(f"Debug logging initialized: {DEBUG_LOG_FILE}", 1)
else:
    def debug_log(message, level=1):
        pass

# ============================================================================
# Original Code
# ============================================================================

if _os_timing.environ.get('TW_TIMING'):
    import atexit as _atexit
    _t0 = _time_module.perf_counter()

    def _report_timing(_f=__file__):
        elapsed = (_time_module.perf_counter() - _t0) * 1000
        import os.path as _osp
        print(f"[timing] {_osp.basename(_f)}: {elapsed:.1f}ms", file=__import__('sys').stderr)

    _atexit.register(_report_timing)

"""
theme-select — ncurses TUI for previewing and selecting Taskwarrior color themes
Part of the awesome-taskwarrior suite.

Usage:
  theme-select              # preview 'next' report
  theme-select <report>     # preview named report (e.g. ready, minimal)
  theme-select --dir PATH   # scan additional themes directory
  theme-select --dev        # use ~/.taskrc-dev / ~/.task-dev
"""

import os
import sys
import re
import curses
import subprocess
import tempfile
import pty
import select
import fcntl
import termios
import struct
from pathlib import Path

VERSION = "0.3.0"

THEME_SEARCH_PATHS = [
    Path.home() / '.task' / 'themes',
    Path('/usr/share/taskwarrior'),
    Path('/usr/local/share/taskwarrior'),
]

THEMES_RC = Path.home() / '.task' / 'config' / 'themes.rc'

LEFT_W   = 27   # theme-list panel width
PREC_W   = 22   # precedence panel width (2-char prefix + up to 20-char name)

# Static curses color pair indices
CP_HEADER   = 1
CP_STATUS   = 2
CP_SELECTED = 3
CP_ACTIVE   = 4
CP_GRABBED  = 5   # precedence item grabbed for moving (black on yellow)

# ANSI-rendered color pairs are allocated dynamically from here
_ANSI_BASE  = 10
_ansi_pairs = {}      # (fg, bg) → pair_number
_ansi_next  = [_ANSI_BASE]

_ANSI_RE = re.compile(r'\x1b\[([0-9;]*)m')
_OSC_RE  = re.compile(r'\x1b\].*?(?:\x1b\\|\x07)', re.DOTALL)   # title bars etc.

_preview_cache = {}   # (str(theme_path), report, width) → [lines]



# ── Colors ─────────────────────────────────────────────────────────────────────

def init_colors():
    curses.start_color()
    curses.use_default_colors()
    curses.init_pair(CP_HEADER,   curses.COLOR_WHITE,  curses.COLOR_BLUE)
    curses.init_pair(CP_STATUS,   curses.COLOR_BLACK,  curses.COLOR_GREEN)
    curses.init_pair(CP_SELECTED, curses.COLOR_BLACK,  curses.COLOR_CYAN)
    curses.init_pair(CP_ACTIVE,   curses.COLOR_GREEN,  -1)
    curses.init_pair(CP_GRABBED,  curses.COLOR_BLACK,  curses.COLOR_YELLOW)


def _ansi_pair(fg, bg):
    key = (fg, bg)
    if key not in _ansi_pairs:
        n = _ansi_next[0]
        _ansi_next[0] += 1
        try:
            curses.init_pair(n, fg, bg)
        except curses.error:
            return 0
        _ansi_pairs[key] = n
    return _ansi_pairs[key]


# ── ANSI → curses ──────────────────────────────────────────────────────────────

def _parse_segments(text):
    """Split ANSI-coded text into [(str, fg, bg, curses_attrs)] segments."""
    fg, bg, attrs = -1, -1, 0
    segments = []
    pos = 0
    A_ITALIC = getattr(curses, 'A_ITALIC', 0)

    for m in _ANSI_RE.finditer(text):
        s, e = m.span()
        if s > pos:
            segments.append((text[pos:s], fg, bg, attrs))
        pos = e
        raw = m.group(1)
        codes = [int(x) for x in raw.split(';') if x] if raw else [0]
        i = 0
        while i < len(codes):
            c = codes[i]
            if   c == 0:                                            fg, bg, attrs = -1, -1, 0
            elif c == 1:                                            attrs |= curses.A_BOLD
            elif c == 2:                                            attrs |= curses.A_DIM
            elif c == 3:                                            attrs |= A_ITALIC
            elif c == 4:                                            attrs |= curses.A_UNDERLINE
            elif c == 7:                                            attrs |= curses.A_REVERSE
            elif 30 <= c <= 37:                                     fg = c - 30
            elif c == 39:                                           fg = -1
            elif 40 <= c <= 47:                                     bg = c - 40
            elif c == 49:                                           bg = -1
            elif 90 <= c <= 97:                                     fg = (c - 90) + 8
            elif 100 <= c <= 107:                                   bg = (c - 100) + 8
            elif c == 38 and i + 2 < len(codes) and codes[i+1] == 5:
                fg = codes[i + 2]; i += 2
            elif c == 48 and i + 2 < len(codes) and codes[i+1] == 5:
                bg = codes[i + 2]; i += 2
            i += 1

    if pos < len(text):
        segments.append((text[pos:], fg, bg, attrs))
    return segments


def addstr_ansi(win, y, x, text, max_w):
    """Write ANSI-colored text to a curses window, clipped to max_w columns."""
    col   = x
    limit = x + max_w
    for chunk, fg, bg, attrs in _parse_segments(text):
        if col >= limit:
            break
        chunk = chunk[:limit - col]
        if not chunk:
            continue
        pair = _ansi_pair(fg, bg)
        try:
            win.addstr(y, col, chunk, attrs | curses.color_pair(pair))
        except curses.error:
            pass
        col += len(chunk)


# ── Theme discovery ────────────────────────────────────────────────────────────

def find_themes(extra_dir=None):
    """Return sorted list of Path objects for all unique .theme files found."""
    search = list(THEME_SEARCH_PATHS)
    if extra_dir:
        search.insert(0, Path(extra_dir).expanduser())
    seen, result = set(), []
    for d in search:
        if not d.exists():
            continue
        for f in sorted(d.glob('*.theme')):
            if f.stem.endswith('.old'):
                continue
            if f.name not in seen:
                seen.add(f.name)
                result.append(f)
    return result


def get_taskrc():
    if 'TASKRC' in os.environ:
        return Path(os.environ['TASKRC'])
    return Path.home() / '.taskrc'


def get_valid_reports():
    """Return set of recognized task report names."""
    try:
        result = subprocess.run(
            ['task', '_show'], capture_output=True, text=True, timeout=5
        )
        reports = set()
        for line in result.stdout.splitlines():
            m = re.match(r'^report\.([^.]+)\.', line)
            if m:
                reports.add(m.group(1))
        return reports
    except Exception:
        return set()


def get_active_theme(themes_rc, taskrc=None):
    """Return Path of the active (uncommented) theme include.

    Reads themes.rc if it exists, otherwise falls back to taskrc (legacy).
    """
    for src in filter(None, [themes_rc, taskrc]):
        try:
            for line in src.read_text().splitlines():
                m = re.match(r'^\s*include\s+(.+\.theme)\s*$', line)
                if m:
                    p = Path(m.group(1).strip()).expanduser()
                    if p.exists():
                        return p
        except Exception:
            pass
    return None


_rule_prec_cache = {}   # str(theme_path) → str

def get_rule_precedence(taskrc, theme_path):
    """Return rule.precedence.color for the given theme via task _show (cached)."""
    key = str(theme_path)
    if key in _rule_prec_cache:
        return _rule_prec_cache[key]
    tmp_rc = _make_preview_rc(taskrc, theme_path)
    try:
        env = os.environ.copy()
        env['TASKRC'] = tmp_rc
        result = subprocess.run(
            ['task', 'rc.hooks=off', '_show'],
            capture_output=True, text=True, env=env, timeout=5,
        )
        for line in result.stdout.splitlines():
            m = re.match(r'^rule\.precedence\.color=(.+)$', line)
            if m:
                val = m.group(1).strip()
                _rule_prec_cache[key] = val
                return val
    except Exception:
        pass
    finally:
        try:
            os.unlink(tmp_rc)
        except Exception:
            pass
    _rule_prec_cache[key] = ''
    return ''


def get_color_legend(taskrc, theme_path, cols):
    """Run 'task colors legend' via PTY with the theme loaded; return ANSI-coded lines (cached)."""
    key = ('legend', str(theme_path), cols)
    if key in _preview_cache:
        return _preview_cache[key]
    tmp_rc = _make_preview_rc(taskrc, theme_path)
    try:
        env = os.environ.copy()
        env['TASKRC'] = tmp_rc
        env['TERM']   = 'xterm-256color'
        raw = _run_in_pty(
            ['task', f'rc.defaultwidth={cols}', 'rc.color=on',
             'rc.hooks=off', 'colors', 'legend'],
            env=env, cols=cols, rows=80,
        )
        lines = _clean_pty(raw).splitlines()
        # drop the TASKRC override warning lines task emits
        lines = [l for l in lines if not re.match(r'^\x1b\[.*?TASKRC override', l)
                                  and not re.match(r'^\x1b\[.*?Configuration override', l)]
    except Exception as e:
        lines = [f'Error: {e}']
    finally:
        try:
            os.unlink(tmp_rc)
        except Exception:
            pass
    _preview_cache[key] = lines
    return lines


def ensure_themes_rc(themes_rc, taskrc, all_themes, active_theme):
    """Create themes.rc if it doesn't exist, and wire it into taskrc once.

    On first run:
      1. Write themes.rc listing all discovered themes (active one uncommented).
      2. In taskrc: comment out any bare theme includes, add `include themes.rc`.
    Subsequent runs: themes.rc already exists, nothing to do.
    """
    if themes_rc.exists():
        return

    themes_rc.parent.mkdir(parents=True, exist_ok=True)
    lines = ['# themes.rc — managed by theme-select\n',
             '# Uncomment exactly one line to activate that theme.\n']
    for path in all_themes:
        is_active = bool(active_theme and path.resolve() == active_theme.resolve())
        prefix = '' if is_active else '#'
        lines.append(f'{prefix}include {path}\n')
    themes_rc.write_text(''.join(lines))

    # Patch taskrc: comment out bare theme includes, inject themes.rc include
    try:
        rc_lines = taskrc.read_text().splitlines(keepends=True)
        new_rc = []
        injected = False
        for line in rc_lines:
            if re.match(r'\s*#?\s*include\s+\S+\.theme', line):
                stripped = line.rstrip('\n')
                if not stripped.lstrip().startswith('#'):
                    new_rc.append(f'#{stripped}\n')
                else:
                    new_rc.append(line)
                if not injected:
                    new_rc.append(f'include {themes_rc}\n')
                    injected = True
            else:
                new_rc.append(line)
        if not injected:
            new_rc.append(f'include {themes_rc}\n')
        taskrc.write_text(''.join(new_rc))
    except Exception:
        pass  # taskrc patch is best-effort; themes.rc still works if included manually


# ── Preview via pseudo-tty ─────────────────────────────────────────────────────

_THEME_LINE_RE = re.compile(
    r'\s*#?\s*include\s+\S+\.theme'       # direct .theme include (active or commented)
    r'|\s*include\s+\S+themes\.rc'        # themes.rc delegation line
)

def _make_preview_rc(taskrc, theme_path):
    """Write a temp TASKRC with all theme/themes.rc includes replaced by theme_path."""
    lines = taskrc.read_text().splitlines(keepends=True)
    new_lines = []
    injected = False
    for line in lines:
        if _THEME_LINE_RE.match(line):
            if not injected:
                new_lines.append(f'include {theme_path}\n')
                injected = True
            # suppress all other theme-related includes
        else:
            new_lines.append(line)
    if not injected:
        new_lines.append(f'include {theme_path}\n')
    tmp = tempfile.NamedTemporaryFile(mode='w', suffix='.taskrc', delete=False)
    tmp.write(''.join(new_lines))
    tmp.close()
    return tmp.name


def _run_in_pty(cmd, env, cols, rows):
    """Run cmd in a pseudo-tty sized (cols × rows), return decoded output."""
    master_fd, slave_fd = pty.openpty()
    winsize = struct.pack('HHHH', rows, cols, 0, 0)
    fcntl.ioctl(slave_fd, termios.TIOCSWINSZ, winsize)

    proc = subprocess.Popen(
        cmd, env=env,
        stdin=slave_fd, stdout=slave_fd, stderr=slave_fd,
        close_fds=True,
    )
    os.close(slave_fd)

    buf = b''
    while True:
        try:
            r, _, _ = select.select([master_fd], [], [], 0.2)
            if r:
                buf += os.read(master_fd, 4096)
            elif proc.poll() is not None:
                # Drain any remaining bytes
                try:
                    while True:
                        r2, _, _ = select.select([master_fd], [], [], 0.05)
                        if r2:
                            buf += os.read(master_fd, 4096)
                        else:
                            break
                except OSError:
                    pass
                break
        except OSError:
            break

    try:
        os.close(master_fd)
    except OSError:
        pass
    proc.wait()
    return buf.decode('utf-8', errors='replace')


def _clean_pty(text):
    """Strip OSC sequences (title bars) and carriage returns left by pty."""
    text = _OSC_RE.sub('', text)
    return text.replace('\r\n', '\n').replace('\r', '')


def get_preview(taskrc, theme_path, report, cols, prec_override=None):
    """Return list of output lines for the given theme/report (cached).

    prec_override: if set, passed as rc.rule.precedence.color= to the task
    subprocess so the live reorder is reflected without writing to the file.
    """
    key = (str(theme_path), report, cols, prec_override or '')
    if key in _preview_cache:
        return _preview_cache[key]

    tmp_rc = _make_preview_rc(taskrc, theme_path)
    try:
        env = os.environ.copy()
        env['TASKRC'] = tmp_rc
        env['TERM']   = 'xterm-256color'
        rows = 40
        cmd = ['task']
        if prec_override:
            cmd.append(f'rc.rule.precedence.color={prec_override}')
        cmd += [f'rc.defaultwidth={cols}', 'rc.color=on',
                'rc.hooks=off', 'rc.verbose=label,blank', f'rc.limit=18', report]
        raw = _run_in_pty(cmd, env=env, cols=cols, rows=rows)
        lines = _clean_pty(raw).splitlines()
    except Exception as e:
        lines = [f'Error: {e}']
    finally:
        try:
            os.unlink(tmp_rc)
        except Exception:
            pass

    _preview_cache[key] = lines
    return lines


# ── Per-report theme helpers ──────────────────────────────────────────────────

def _resolve_theme_stem(stem):
    """Resolve a theme stem (e.g. 'dark-256') to a Path, or None."""
    for d in THEME_SEARCH_PATHS:
        p = d / f'{stem}.theme'
        if p.exists():
            return p
    return None


def get_report_theme_path(themes_rc, report):
    """Return Path of the theme configured for report, or None."""
    try:
        for line in themes_rc.read_text().splitlines():
            m = re.match(rf'^\s*report\.{re.escape(report)}\.theme\s*=\s*(\S+)', line)
            if m:
                return _resolve_theme_stem(m.group(1))
    except Exception:
        pass
    return None


def set_report_theme(themes_rc, report, theme_path):
    """Write report.<report>.theme=<stem> into themes.rc preamble.

    Updates an existing line (active or commented), or inserts after
    the last report.*.theme= line, or before the first include line.
    """
    stem = theme_path.stem
    new_line = f'report.{report}.theme={stem}\n'
    key_re        = re.compile(rf'^\s*#?\s*report\.{re.escape(report)}\.theme\s*=', re.IGNORECASE)
    any_report_re = re.compile(r'^\s*#?\s*report\.\w+\.theme\s*=')
    include_re    = re.compile(r'^\s*#?\s*include\s+\S+\.theme')

    try:
        lines = themes_rc.read_text().splitlines(keepends=True)
    except FileNotFoundError:
        lines = []

    # Replace existing line for this report (active or commented)
    for i, line in enumerate(lines):
        if key_re.match(line):
            lines[i] = new_line
            themes_rc.write_text(''.join(lines))
            return

    # Insert: after last report.*.theme= line, or before first include, or append
    last_report_idx   = None
    first_include_idx = None
    for i, line in enumerate(lines):
        if any_report_re.match(line):
            last_report_idx = i
        elif first_include_idx is None and include_re.match(line):
            first_include_idx = i

    if last_report_idx is not None:
        lines.insert(last_report_idx + 1, new_line)
    elif first_include_idx is not None:
        lines.insert(first_include_idx, new_line)
    else:
        lines.append(new_line)

    themes_rc.write_text(''.join(lines))


# ── Apply theme (writes only to themes.rc) ────────────────────────────────────

def apply_theme(themes_rc, theme_path, all_themes):
    """Rewrite themes.rc with theme_path as the sole active include.

    Non-include lines (comments, report.*.theme= config) are preserved in place.
    The include block is rebuilt from all_themes at the position of the first
    include line found; if no include lines exist yet, appended at the end.
    """
    try:
        existing = themes_rc.read_text().splitlines(keepends=True)
    except FileNotFoundError:
        existing = []

    # Collect non-include lines to preserve, track where include block starts
    preamble = []
    first_include_idx = None
    for i, line in enumerate(existing):
        if re.match(r'\s*#?\s*include\s+\S+\.theme', line):
            if first_include_idx is None:
                first_include_idx = i
        else:
            if first_include_idx is None:
                preamble.append(line)
            # lines after the include block (trailing comments etc.) are dropped
            # to keep the file clean — only preamble is preserved

    include_lines = []
    for path in all_themes:
        is_active = path.resolve() == theme_path.resolve()
        prefix = '' if is_active else '#'
        include_lines.append(f'{prefix}include {path}\n')

    themes_rc.write_text(''.join(preamble + include_lines))


# ── Drawing ────────────────────────────────────────────────────────────────────

LEGEND_W = 52   # color legend panel width


# ── Color picker helpers ───────────────────────────────────────────────────────

def _strip_ansi(text):
    return re.sub(r'\x1b\[[0-9;]*[mK]', '', text)


def _parse_legend_line(ansi_line):
    """Extract (color_name, current_value) from a task colors legend line."""
    text = _strip_ansi(ansi_line).strip()
    m = re.match(r'^(color\.\S+)\s*(.*?)\s*$', text)
    if m:
        return m.group(1), m.group(2).strip()
    return None, None


def _parse_color_value(value):
    """Split 'bold white on red' → ('bold white', 'red'). Handles on-only and fg-only."""
    m = re.match(r'^on\s+(.+)$', value.strip())
    if m:
        return '', m.group(1).strip()
    parts = re.split(r'\s+on\s+', value.strip(), maxsplit=1)
    if len(parts) == 2:
        return parts[0].strip(), parts[1].strip()
    return value.strip(), ''


def _rebuild_color_value(fg, bg):
    fg, bg = fg.strip(), bg.strip()
    if fg and bg:
        return f"{fg} on {bg}"
    return fg or (f"on {bg}" if bg else '')


def edit_theme_color(theme_path, color_name, new_value):
    """Rewrite color_name=new_value in the theme file. Returns (ok, message)."""
    if not os.access(theme_path, os.W_OK):
        return False, f"Read-only: {theme_path.name} — copy to ~/.task/themes/ to edit"
    try:
        lines = theme_path.read_text().splitlines(keepends=True)
    except Exception as e:
        return False, f"Cannot read: {e}"
    pat = re.compile(rf'^\s*#?\s*{re.escape(color_name)}\s*=')
    found = False
    new_lines = []
    for line in lines:
        if pat.match(line) and not found:
            new_lines.append(f"{color_name}={new_value}\n")
            found = True
        else:
            new_lines.append(line)
    if not found:
        new_lines.append(f"{color_name}={new_value}\n")
    try:
        theme_path.write_text(''.join(new_lines))
        return True, f"Updated: {color_name}={new_value}"
    except Exception as e:
        return False, f"Write failed: {e}"


_swatch_cache = {}   # cols → lines

def get_color_swatches(taskrc, theme_path, cols):
    """Run 'task colors' (full swatch table) via PTY. Cached by width."""
    if cols in _swatch_cache:
        return _swatch_cache[cols]
    tmp_rc = _make_preview_rc(taskrc, theme_path)
    try:
        env = os.environ.copy()
        env['TASKRC'] = tmp_rc
        env['TERM']   = 'xterm-256color'
        raw = _run_in_pty(
            ['task', f'rc.defaultwidth={cols}', 'rc.color=on', 'rc.hooks=off', 'colors'],
            env=env, cols=cols, rows=80,
        )
        lines = _clean_pty(raw).splitlines()
        lines = [l for l in lines
                 if not re.match(r'^\x1b\[.*?(?:TASKRC override|Configuration override)', l)]
    except Exception as e:
        lines = [f'Error: {e}']
    finally:
        try:
            os.unlink(tmp_rc)
        except Exception:
            pass
    _swatch_cache[cols] = lines
    return lines


def color_picker_popup(stdscr, taskrc, theme_path, color_name, current_value):
    """
    Popup editor for a single theme color entry.
    Shows 'task colors' swatch as scrollable reference.
    Two input fields: fg / bg (Tab to switch).
    Returns new value string, or None if cancelled.
    """
    h, w = stdscr.getmaxyx()
    pop_h = min(h - 2, 38)
    pop_w = min(w - 2, 84)
    pop_y = max(0, (h - pop_h) // 2)
    pop_x = max(0, (w - pop_w) // 2)
    inner_w = pop_w - 2

    # swatch area = popup minus: 2 borders + 1 title + 1 blank + 2 inputs + 1 preview + 1 hint
    swatch_h = max(3, pop_h - 8)

    swatch_lines = get_color_swatches(taskrc, theme_path, inner_w)
    fg_input, bg_input = _parse_color_value(current_value)
    swatch_scroll = 0
    focus = 0   # 0=fg, 1=bg

    win = curses.newwin(pop_h, pop_w, pop_y, pop_x)
    win.keypad(True)

    while True:
        win.erase()
        win.box()

        # Title
        title = f' {color_name} '
        try:
            win.addstr(0, max(1, (pop_w - len(title)) // 2), title,
                       curses.A_BOLD | curses.color_pair(CP_HEADER))
        except curses.error:
            pass

        # Swatch
        for i in range(swatch_h):
            src_i = i + swatch_scroll
            if src_i >= len(swatch_lines):
                break
            addstr_ansi(win, 1 + i, 1, swatch_lines[src_i], inner_w)

        base = 1 + swatch_h + 1   # row after blank separator

        # fg field
        fg_attr = curses.A_REVERSE if focus == 0 else 0
        fg_disp = (fg_input + ' ').ljust(inner_w - 4)[:inner_w - 4]
        try:
            win.addstr(base,     1, 'fg: ')
            win.addstr(base,     5, fg_disp, fg_attr)
        except curses.error:
            pass

        # bg field
        bg_attr = curses.A_REVERSE if focus == 1 else 0
        bg_disp = (bg_input + ' ').ljust(inner_w - 4)[:inner_w - 4]
        try:
            win.addstr(base + 1, 1, 'bg: ')
            win.addstr(base + 1, 5, bg_disp, bg_attr)
        except curses.error:
            pass

        # Preview: render a sample in the described color
        preview_val = _rebuild_color_value(fg_input, bg_input)
        sample = f"  {preview_val or '(none)'}  "
        try:
            win.addstr(base + 2, 1, 'preview: ')
            addstr_ansi(win, base + 2, 10, sample, inner_w - 10)
        except curses.error:
            pass

        # Hint
        hint = ' Tab fg/bg   ↑↓ scroll   Enter apply   Esc cancel'
        try:
            win.addstr(pop_h - 2, 1, hint[:inner_w], curses.color_pair(CP_STATUS))
        except curses.error:
            pass

        win.refresh()
        key = win.getch()

        if key == 27:
            return None
        elif key in (10, 13):
            return _rebuild_color_value(fg_input, bg_input)
        elif key == ord('\t'):
            focus = 1 - focus
        elif key == curses.KEY_UP:
            swatch_scroll = max(0, swatch_scroll - 1)
        elif key == curses.KEY_DOWN:
            swatch_scroll = min(max(0, len(swatch_lines) - swatch_h), swatch_scroll + 1)
        elif key in (curses.KEY_BACKSPACE, 127, 8):
            if focus == 0:
                fg_input = fg_input[:-1]
            else:
                bg_input = bg_input[:-1]
        elif 32 <= key <= 126:
            if focus == 0:
                fg_input += chr(key)
            else:
                bg_input += chr(key)


def _panel_layout(w, show_prec, show_legend):
    """Return (use_prec, use_legend, right_x, preview_w, prec_x, legend_x) for width w."""
    right_x   = LEFT_W + 1
    min_core  = LEFT_W + 2 + 20   # list + divider + min preview

    use_prec   = show_prec   and w >= min_core + 2 + PREC_W
    min_w_leg  = min_core + (2 + PREC_W if use_prec else 0) + 2 + LEGEND_W
    use_legend = show_legend and w >= min_w_leg

    if use_prec and use_legend:
        legend_x  = w - LEGEND_W
        prec_x    = legend_x - 1 - PREC_W
        preview_w = max(1, prec_x - 1 - right_x)
    elif use_prec:
        prec_x    = w - PREC_W
        legend_x  = None
        preview_w = max(1, prec_x - 1 - right_x)
    elif use_legend:
        legend_x  = w - LEGEND_W
        prec_x    = None
        preview_w = max(1, legend_x - 1 - right_x)
    else:
        prec_x = legend_x = None
        preview_w = max(1, w - right_x)

    return use_prec, use_legend, right_x, preview_w, prec_x, legend_x


def draw(stdscr, themes, cursor, scroll, active_theme, preview_lines, report, message,
         configure_mode=False, for_report=None,
         show_legend=False, legend_lines=None, legend_scroll=0,
         legend_focus=False, legend_cursor=0, rule_prec='',
         show_prec=False, prec_items=None, prec_cursor=0,
         prec_focus=False, prec_grabbed=False, prec_scroll=0):
    h, w = stdscr.getmaxyx()
    stdscr.erase()

    HDR_ROWS = 2
    list_h   = h - HDR_ROWS - 1

    use_prec, use_legend, right_x, preview_w, prec_x, legend_x = \
        _panel_layout(w, show_prec, show_legend)

    div1_x = LEFT_W

    # ── Header row 0 ───────────────────────────────────────────────────────────
    if configure_mode:
        hdr_l = f"  theme-select v{VERSION}  [for: {for_report}]"
    else:
        hdr_l = f"  theme-select v{VERSION}  [{report}]"
    hdr_r = f"  {cursor + 1}/{len(themes)}  "
    try:
        stdscr.addstr(0, 0, hdr_l[:w - 1], curses.color_pair(CP_HEADER))
        if len(hdr_r) < w:
            stdscr.addstr(0, w - len(hdr_r), hdr_r, curses.color_pair(CP_HEADER))
    except curses.error:
        pass

    # ── Header row 1: rule.precedence.color ────────────────────────────────────
    prec_hdr = f"  rule.precedence.color={rule_prec}" if rule_prec else \
               "  rule.precedence.color=(loading...)"
    try:
        stdscr.addstr(1, 0, prec_hdr[:w - 1].ljust(w - 1), curses.color_pair(CP_HEADER))
    except curses.error:
        pass

    # ── Left panel: theme list ─────────────────────────────────────────────────
    for i, path in enumerate(themes):
        if i < scroll or i >= scroll + list_h:
            continue
        row = HDR_ROWS + (i - scroll)
        selected  = (i == cursor)
        is_active = bool(active_theme and path.resolve() == active_theme.resolve())

        arrow  = '>' if selected else ' '
        marker = ' *' if is_active else '  '
        label  = f" {arrow} {path.stem}{marker}"[:LEFT_W].ljust(LEFT_W)

        if selected:
            attr = curses.color_pair(CP_SELECTED) | curses.A_BOLD
        elif is_active:
            attr = curses.color_pair(CP_ACTIVE) | curses.A_BOLD
        else:
            attr = 0
        try:
            stdscr.addstr(row, 0, label, attr)
        except curses.error:
            pass

    # ── Divider 1 (list | preview) ─────────────────────────────────────────────
    for row in range(HDR_ROWS, h - 1):
        try:
            stdscr.addch(row, div1_x, curses.ACS_VLINE)
        except curses.error:
            pass

    # ── Middle panel: colored report preview ───────────────────────────────────
    for i, line in enumerate(preview_lines):
        row = HDR_ROWS + i
        if row >= h - 1:
            break
        addstr_ansi(stdscr, row, right_x, line, preview_w - 1)

    # ── Precedence panel ───────────────────────────────────────────────────────
    if use_prec and prec_x is not None:
        div_prec = prec_x - 1
        for row in range(HDR_ROWS, h - 1):
            try:
                stdscr.addch(row, div_prec, curses.ACS_VLINE)
            except curses.error:
                pass
        items = prec_items or []
        for i in range(list_h):
            src_i = i + prec_scroll
            if src_i >= len(items):
                break
            row   = HDR_ROWS + i
            is_sel     = prec_focus and (i == prec_cursor)
            is_grab    = is_sel and prec_grabbed
            if is_grab:
                attr = curses.color_pair(CP_GRABBED) | curses.A_BOLD
                pfx  = '* '
            elif is_sel:
                attr = curses.color_pair(CP_SELECTED) | curses.A_BOLD
                pfx  = '> '
            else:
                attr = 0
                pfx  = '  '
            label = (pfx + items[src_i])[:PREC_W].ljust(PREC_W)
            try:
                stdscr.addstr(row, prec_x, label, attr)
            except curses.error:
                pass

    # ── Legend panel ───────────────────────────────────────────────────────────
    if use_legend and legend_x is not None:
        div_leg = legend_x - 1
        for row in range(HDR_ROWS, h - 1):
            try:
                stdscr.addch(row, div_leg, curses.ACS_VLINE)
            except curses.error:
                pass
        lines = legend_lines or []
        for i in range(list_h):
            src_i = i + legend_scroll
            if src_i >= len(lines):
                break
            row = HDR_ROWS + i
            is_cur   = legend_focus and (i == legend_cursor)
            ind_ch   = ord('>') if is_cur else ord(' ')
            ind_attr = curses.color_pair(CP_SELECTED) | curses.A_BOLD if is_cur else 0
            try:
                stdscr.addch(row, legend_x, ind_ch, ind_attr)
            except curses.error:
                pass
            addstr_ansi(stdscr, row, legend_x + 1, lines[src_i], LEGEND_W - 2)

    # ── Status bar ─────────────────────────────────────────────────────────────
    if prec_focus and use_prec:
        if prec_grabbed:
            panel_hint = "p hide  ↑↓ move-item  Enter save  Esc cancel"
        else:
            panel_hint = "p hide  Tab next-panel  ↑↓ navigate  Enter grab"
    elif legend_focus and use_legend:
        panel_hint = "l hide  Tab next-panel  ↑↓ navigate  Enter edit-color"
    elif use_prec or use_legend:
        panel_hint = ("p focus" if use_prec else "") + \
                     ("  " if use_prec and use_legend else "") + \
                     ("l focus" if use_legend else "")
    else:
        panel_hint = "p precedence  l legend"

    if configure_mode:
        default_bar = f"  jk themes   Space set-{for_report}-theme   e edit   r refresh   {panel_hint}   q quit"
    else:
        default_bar = f"  jk themes   Space apply   e edit   r refresh   {panel_hint}   q quit"
    bar = message or default_bar
    try:
        stdscr.addstr(h - 1, 0, bar[:w - 1].ljust(w - 1), curses.color_pair(CP_STATUS))
    except curses.error:
        pass

    stdscr.refresh()


# ── Main loop ──────────────────────────────────────────────────────────────────

def run(stdscr, themes, themes_rc, taskrc, report, for_report=None):
    configure_mode = for_report is not None
    curses.curs_set(0)
    init_colors()
    stdscr.keypad(True)

    if not themes:
        stdscr.addstr(0, 0, "No .theme files found")
        stdscr.getch()
        return

    def _get_active():
        if configure_mode:
            return get_report_theme_path(themes_rc, for_report)
        return get_active_theme(themes_rc, taskrc)

    active_theme = _get_active()
    cursor = next(
        (i for i, p in enumerate(themes)
         if active_theme and p.resolve() == active_theme.resolve()),
        0,
    )
    scroll        = 0
    message       = ''
    preview_lines = []
    last_theme    = None
    last_prec_ovr = None    # tracks live-reorder override for preview cache
    # legend panel
    show_legend   = False
    legend_focus  = False
    legend_lines  = []
    legend_scroll = 0
    legend_cursor = 0
    # precedence panel
    show_prec     = False
    prec_focus    = False
    prec_items    = []      # working copy of rule.precedence.color tokens
    prec_saved    = []      # saved copy for Esc-cancel
    prec_cursor   = 0
    prec_scroll   = 0
    prec_grabbed  = False   # item at cursor is held for reordering
    rule_prec     = ''

    while True:
        h, w    = stdscr.getmaxyx()
        list_h  = h - 3      # 2 header rows + 1 status bar
        _, _, _, preview_w, _, _ = _panel_layout(w, show_prec, show_legend)

        if cursor < scroll:
            scroll = cursor
        elif cursor >= scroll + list_h:
            scroll = cursor - list_h + 1

        theme_path = themes[cursor]
        prec_ovr   = ','.join(prec_items) if prec_grabbed else None

        if theme_path != last_theme:
            # theme changed — cancel any in-flight grab, reload everything
            if prec_grabbed:
                prec_items   = prec_saved[:]
                prec_grabbed = False
            rule_prec    = get_rule_precedence(taskrc, theme_path)
            preview_lines = get_preview(taskrc, theme_path, report, preview_w)
            if show_legend:
                legend_lines  = get_color_legend(taskrc, theme_path, LEGEND_W)
                legend_scroll = 0
                legend_cursor = 0
            if show_prec:
                prec_items  = [x.strip() for x in rule_prec.split(',') if x.strip()]
                prec_cursor = 0
                prec_scroll = 0
            last_theme    = theme_path
            last_prec_ovr = None
        elif prec_ovr != last_prec_ovr:
            # same theme, but live reorder changed — refresh preview only
            preview_lines = get_preview(taskrc, theme_path, report, preview_w, prec_ovr)
            last_prec_ovr = prec_ovr

        draw(stdscr, themes, cursor, scroll, active_theme, preview_lines, report, message,
             configure_mode=configure_mode, for_report=for_report,
             show_legend=show_legend, legend_lines=legend_lines,
             legend_scroll=legend_scroll, legend_focus=legend_focus,
             legend_cursor=legend_cursor, rule_prec=rule_prec,
             show_prec=show_prec, prec_items=prec_items,
             prec_cursor=prec_cursor, prec_focus=prec_focus,
             prec_grabbed=prec_grabbed, prec_scroll=prec_scroll)
        message = ''

        key = stdscr.getch()

        # ── Quit / cancel grab ─────────────────────────────────────────────────
        if key == 27:   # Esc
            if prec_grabbed:
                prec_items   = prec_saved[:]
                prec_grabbed = False
                last_prec_ovr = None
                _preview_cache.clear()
                last_theme = None
            else:
                break
        elif key in (ord('q'), ord('Q')):
            break

        # ── Panel toggles (auto-focus on open) ────────────────────────────────
        elif key == ord('l'):
            show_legend = not show_legend
            if show_legend:
                if not legend_lines:
                    legend_lines  = get_color_legend(taskrc, theme_path, LEGEND_W)
                    legend_scroll = 0
                    legend_cursor = 0
                legend_focus = True
                prec_focus   = False
            else:
                legend_focus = False

        elif key == ord('p'):
            show_prec = not show_prec
            if show_prec:
                if not prec_items:
                    prec_items  = [x.strip() for x in rule_prec.split(',') if x.strip()]
                    prec_cursor = 0
                    prec_scroll = 0
                prec_focus   = True
                legend_focus = False
            else:
                prec_focus   = False
                prec_grabbed = False

        # ── Tab: cycle focus between open panels ──────────────────────────────
        elif key == ord('\t'):
            if prec_focus and show_prec:
                prec_focus = False
                if show_legend:
                    legend_focus  = True
                    legend_cursor = 0
            elif legend_focus and show_legend:
                legend_focus = False
            else:
                # focus first open panel
                if show_prec:
                    prec_focus   = True
                    prec_cursor  = 0
                elif show_legend:
                    legend_focus  = True
                    legend_cursor = 0

        # ── Arrow keys: context-sensitive ─────────────────────────────────────
        elif key == curses.KEY_UP:
            if prec_focus and show_prec:
                if prec_grabbed:
                    abs_i = prec_scroll + prec_cursor
                    if abs_i > 0:
                        prec_items[abs_i], prec_items[abs_i - 1] = \
                            prec_items[abs_i - 1], prec_items[abs_i]
                        if prec_cursor > 0:
                            prec_cursor -= 1
                        else:
                            prec_scroll -= 1
                        last_prec_ovr = None   # trigger preview refresh
                else:
                    if prec_cursor > 0:
                        prec_cursor -= 1
                    elif prec_scroll > 0:
                        prec_scroll -= 1
            elif legend_focus and show_legend:
                if legend_cursor > 0:
                    legend_cursor -= 1
                elif legend_scroll > 0:
                    legend_scroll -= 1
            elif cursor > 0:
                cursor -= 1

        elif key == curses.KEY_DOWN:
            if prec_focus and show_prec:
                if prec_grabbed:
                    abs_i = prec_scroll + prec_cursor
                    if abs_i + 1 < len(prec_items):
                        prec_items[abs_i], prec_items[abs_i + 1] = \
                            prec_items[abs_i + 1], prec_items[abs_i]
                        if prec_cursor < list_h - 1:
                            prec_cursor += 1
                        else:
                            prec_scroll += 1
                        last_prec_ovr = None   # trigger preview refresh
                else:
                    total    = len(prec_items)
                    abs_pos  = prec_scroll + prec_cursor
                    if abs_pos + 1 < total:
                        if prec_cursor < list_h - 1:
                            prec_cursor += 1
                        else:
                            prec_scroll += 1
            elif legend_focus and show_legend:
                total   = len(legend_lines)
                abs_pos = legend_scroll + legend_cursor
                if abs_pos + 1 < total:
                    if legend_cursor < list_h - 1:
                        legend_cursor += 1
                    else:
                        legend_scroll += 1
            elif cursor < len(themes) - 1:
                cursor += 1

        # ── j/k always navigate the theme list ────────────────────────────────
        elif key == ord('k'):
            if cursor > 0:
                cursor -= 1

        elif key == ord('j'):
            if cursor < len(themes) - 1:
                cursor += 1

        # ── g/G: jump to top/bottom of focused panel ──────────────────────────
        elif key == ord('g'):
            if prec_focus:
                prec_scroll = 0
                prec_cursor = 0
            elif legend_focus:
                legend_scroll = 0
                legend_cursor = 0
            else:
                cursor = 0

        elif key == ord('G'):
            if prec_focus:
                total       = len(prec_items)
                prec_scroll = max(0, total - list_h)
                prec_cursor = min(list_h - 1, total - 1 - prec_scroll)
            elif legend_focus:
                total         = len(legend_lines)
                legend_scroll = max(0, total - list_h)
                legend_cursor = min(list_h - 1, total - 1 - legend_scroll)
            else:
                cursor = len(themes) - 1

        # ── Enter: grab/save (prec) or open picker (legend) ───────────────────
        elif key in (10, 13) and prec_focus and show_prec:
            if prec_grabbed:
                # save new order to theme file
                new_prec = ','.join(prec_items)
                ok, msg  = edit_theme_color(theme_path, 'rule.precedence.color', new_prec)
                message  = msg
                prec_grabbed  = False
                prec_saved    = []
                if ok:
                    _preview_cache.clear()
                    _rule_prec_cache.clear()
                    last_theme    = None
                    last_prec_ovr = None
            else:
                # grab the item at cursor
                if prec_items:
                    prec_saved   = prec_items[:]
                    prec_grabbed = True

        elif key in (10, 13) and legend_focus and show_legend:
            line_idx = legend_scroll + legend_cursor
            if line_idx < len(legend_lines):
                color_name, current_val = _parse_legend_line(legend_lines[line_idx])
                if color_name:
                    new_val = color_picker_popup(
                        stdscr, taskrc, theme_path, color_name, current_val)
                    stdscr.clear()   # force full repaint to clear popup artifacts
                    if new_val is not None:
                        ok, msg = edit_theme_color(theme_path, color_name, new_val)
                        message = msg
                        if ok:
                            _preview_cache.clear()
                            _rule_prec_cache.clear()
                            _swatch_cache.clear()
                            last_theme    = None
                            last_prec_ovr = None
                            legend_lines  = []
                            legend_scroll = 0
                            legend_cursor = 0
                            prec_items    = []   # reload prec list too
                            continue

        elif key in (ord(' '), 10, 13):
            if configure_mode:
                set_report_theme(themes_rc, for_report, themes[cursor])
                active_theme = themes[cursor]
                _preview_cache.clear()
                message = f"Set {for_report} theme: {themes[cursor].stem}"
            else:
                apply_theme(themes_rc, themes[cursor], themes)
                active_theme = themes[cursor]
                _preview_cache.clear()
                message = f"Applied: {themes[cursor].stem}"

        elif key == ord('e'):
            editor = os.environ.get('VISUAL') or os.environ.get('EDITOR') or 'vi'
            curses.endwin()
            subprocess.run([editor, str(themes[cursor])])
            stdscr.refresh()
            _preview_cache.clear()
            active_theme  = _get_active()
            last_theme    = None
            last_prec_ovr = None
            prec_items    = []
            prec_grabbed  = False
            message = f"Returned from {os.path.basename(editor)}"

        elif key == ord('r'):
            _preview_cache.clear()
            _rule_prec_cache.clear()
            active_theme  = _get_active()
            last_theme    = None
            last_prec_ovr = None
            legend_lines  = []
            prec_items    = []
            prec_grabbed  = False
            message = "Refreshed"

        elif key == curses.KEY_RESIZE:
            _preview_cache.clear()
            last_theme    = None
            last_prec_ovr = None


# ── Entry point ────────────────────────────────────────────────────────────────

def main():
    import argparse
    parser = argparse.ArgumentParser(
        description=f"theme-select v{VERSION} — preview and select Taskwarrior color themes"
    )
    parser.add_argument('report', nargs='?', default=None,
                        help='Report to preview; if given, also sets report.<name>.theme= on apply')
    parser.add_argument('--dir', metavar='PATH',
                        help='additional directory to scan for .theme files')
    parser.add_argument('--dev', action='store_true',
                        help='use ~/.taskrc-dev / ~/.task-dev (dev environment)')
    parser.add_argument('--version', action='version', version=f'%(prog)s {VERSION}')
    args = parser.parse_args()

    if args.dev:
        os.environ.setdefault('TASKRC',      str(Path.home() / '.taskrc-dev'))
        os.environ.setdefault('TW_TASK_DIR', str(Path.home() / '.task-dev'))

    taskrc = get_taskrc()
    if not taskrc.exists():
        print(f"TASKRC not found: {taskrc}", file=sys.stderr)
        sys.exit(1)

    themes = find_themes(args.dir)
    if not themes:
        print("No .theme files found", file=sys.stderr)
        sys.exit(1)

    themes_rc = THEMES_RC
    active_theme = get_active_theme(themes_rc, taskrc)
    ensure_themes_rc(themes_rc, taskrc, themes, active_theme)

    for_report     = args.report                     # None = normal mode
    preview_report = args.report or 'next'           # always have a report to preview

    if for_report is not None:
        valid = get_valid_reports()
        if valid and for_report not in valid:
            print(f"theme-select: '{for_report}' is not a recognized report name", file=sys.stderr)
            sys.exit(1)

    try:
        curses.wrapper(run, themes, themes_rc, taskrc, preview_report, for_report)
    except KeyboardInterrupt:
        pass


if __name__ == '__main__':
    main()
